version: "3"
services:
  web:
    build: "."
    image: "stan/gospodar"
    container_name: "gospodar_web"
    depends_on:
      - "db"
    environment:
      - "PORT=3000"
    volumes:
      - ".:/go/src/gospodar"
    ports:
      - "3000:3000"
  db:
    container_name: "gospodar_db"
    image: "postgres"
    command: "psql -U postgres -h gospodar_db -c 'CREATE DATABASE gospodar_development;'"
    ports:
      - "5432:5432"
