version: "3"
services:
  web:
    build: "."
    image: "stan/gospodar"
    container_name: "gospodar_web"
    environment:
      - "PORT=3000"
    volumes:
      - ".:/go/src"
    ports:
      - "3000:3000"
